### ISSUE TITLE
If ACLs are disabled, it should not require the file to exist

### ISSUE THREAD

**Issue by ogarcia** [rustic-rs/rustic_server#60]
Let's take this configuration as an example:
```toml
[acl]
acl-path = "/test_data/test_repo/acl.toml"
private-repo = false
append-only = false
```

Since I have `private-repo` set to `false` it should not even access the ACL file. However when I run the application it gives an error:
```
% ./rustic-server -c rustic-server.toml serve
error: storage error: Could not create ACL due to Internal server error: `Could not read toml file: No such file or directory (os error 2) at "/etc/rustic-server/acl.toml"`
```

On the other hand I think it is more descriptive to use a `disable-acl` key (in the style of `disable-auth`) than `private-repo`.
